In [1]:
import numpy as np
import torch

In [2]:
#Rating, Popularity
inputs = np.array(
    [
        [9.17, 1/3],     
        [9.10, 1/10],        
        [7.99, 1/20],        
        [8.77, 1/44],        
        [8.82, 1/92],        
        [8.25, 1/161],       
        [8.60, 1/360],       
        [7.83, 1/552]        
    ],
    dtype="float32"
)

#Members, User-Ratings 
targets = np.array(
     [
         [2489000, 1514000],
         [1958000, 1047000],
         [1692000, 996400],
         [1378400, 669000],
         [983500, 595000],
         [688000, 368000],
         [415600, 83200],
         [287500, 124000],
     ],
     dtype="float32"
)
targets = targets/100000

In [3]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

print(inputs,"\n", targets)

tensor([[9.1700e+00, 3.3333e-01],
        [9.1000e+00, 1.0000e-01],
        [7.9900e+00, 5.0000e-02],
        [8.7700e+00, 2.2727e-02],
        [8.8200e+00, 1.0870e-02],
        [8.2500e+00, 6.2112e-03],
        [8.6000e+00, 2.7778e-03],
        [7.8300e+00, 1.8116e-03]]) 
 tensor([[24.8900, 15.1400],
        [19.5800, 10.4700],
        [16.9200,  9.9640],
        [13.7840,  6.6900],
        [ 9.8350,  5.9500],
        [ 6.8800,  3.6800],
        [ 4.1560,  0.8320],
        [ 2.8750,  1.2400]], dtype=torch.float64)


In [4]:
#weights matrix
w = torch.randn(2, 2, requires_grad=True)
b = torch.randn(2, requires_grad=True)

print(w, "\n", b)

tensor([[ 0.8313, -0.3541],
        [-0.5900, -0.8204]], requires_grad=True) 
 tensor([1.0943, 0.7514], requires_grad=True)


In [5]:
def model(x):
    return x @ w.t() + b

In [6]:
predictions = model(inputs)

print(predictions)  
print(targets)

tensor([[ 8.5993, -4.9329],
        [ 8.6237, -4.7001],
        [ 7.7187, -4.0041],
        [ 8.3768, -4.4420],
        [ 8.4225, -4.4618],
        [ 7.9503, -4.1216],
        [ 8.2425, -4.3253],
        [ 7.6027, -3.8702]], grad_fn=<AddBackward0>)
tensor([[24.8900, 15.1400],
        [19.5800, 10.4700],
        [16.9200,  9.9640],
        [13.7840,  6.6900],
        [ 9.8350,  5.9500],
        [ 6.8800,  3.6800],
        [ 4.1560,  0.8320],
        [ 2.8750,  1.2400]], dtype=torch.float64)


In [7]:
#mean squared error
def mse(t1, t2):
    diff = t1 - t2
    #error is squared and added and divided by total number of elements
    return torch.sum(diff*diff)/diff.numel()

In [8]:
loss = mse(predictions, targets)
print(loss)

tensor(107.2242, dtype=torch.float64, grad_fn=<DivBackward0>)


In [9]:
loss.backward()

In [10]:
print(w)
print(w.grad)

print(b)
print(b.grad)


tensor([[ 0.8313, -0.3541],
        [-0.5900, -0.8204]], requires_grad=True)
tensor([[-37.6867,  -0.8872],
        [-96.4888,  -1.1681]])
tensor([1.0943, 0.7514], requires_grad=True)
tensor([ -4.1729, -11.1030])


In [11]:
for i in range(600):
    preds = model(inputs)
    loss = mse(preds, targets)

    if(i%10==0):
        print(loss)

    loss.backward()
    
    with torch.no_grad():
        w -= w.grad * 0.0001
        b -= b.grad * 1e-4
        w.grad.zero_()
        b.grad.zero_()

tensor(107.2242, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(96.1485, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(87.5527, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(80.1524, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(73.7813, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(68.2962, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(63.5739, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(59.5083, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(56.0081, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(52.9946, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(50.4002, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(48.1666, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(46.2435, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(44.5878, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(43.1623, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(41.9350, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(40.8784, dtype=t

In [12]:
print(w)
print(preds)

tensor([[ 1.3318, -0.3150],
        [ 0.6896, -0.7867]], requires_grad=True)
tensor([[13.2470,  6.9527],
        [13.2273,  7.0880],
        [11.7648,  6.3620],
        [12.8122,  6.9213],
        [12.8825,  6.9651],
        [12.1249,  6.5757],
        [12.5921,  6.8198],
        [11.5669,  6.2896]], grad_fn=<AddBackward0>)


In [13]:
predictions = preds*100000
print(predictions)

print(w)
print(b)

tensor([[1324704.0000,  695269.1250],
        [1322732.6250,  708799.7500],
        [1176481.1250,  636203.5625],
        [1281218.6250,  692126.8750],
        [1288250.8750,  696507.0000],
        [1212486.7500,  657574.4375],
        [1259207.0000,  681975.5625],
        [1156691.0000,  628963.3750]], grad_fn=<MulBackward0>)
tensor([[ 1.3318, -0.3150],
        [ 0.6896, -0.7867]], requires_grad=True)
tensor([1.1397, 0.8926], requires_grad=True)


In [14]:
members = (8.92 *  1.2807 + 9 *0.0855) * 100000
users = (8.92*0.8601 +9*1.6151)*100000
print(members)
print(users)

1219334.4
2220799.2
