In [1]:
import numpy as np
import torch

In [2]:
#Rating, Popularity
inputs = np.array(
    [
        [9.17, 1/3],     
        [9.10, 1/10],        
        [7.99, 1/20],        
        [8.77, 1/44],        
        [8.82, 1/92],        
        [8.25, 1/161],       
        [8.60, 1/360],       
        [7.83, 1/552]        
    ],
    dtype="float32"
)

#Members, User-Ratings 
targets = np.array(
     [
         [2489000, 1514000],
         [1958000, 1047000],
         [1692000, 996400],
         [1378400, 669000],
         [983500, 595000],
         [688000, 368000],
         [415600, 83200],
         [287500, 124000],
     ],
     dtype="float32"
)
targets = targets/100000

In [3]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

print(inputs,"\n", targets)

tensor([[9.1700e+00, 3.3333e-01],
        [9.1000e+00, 1.0000e-01],
        [7.9900e+00, 5.0000e-02],
        [8.7700e+00, 2.2727e-02],
        [8.8200e+00, 1.0870e-02],
        [8.2500e+00, 6.2112e-03],
        [8.6000e+00, 2.7778e-03],
        [7.8300e+00, 1.8116e-03]]) 
 tensor([[24.8900, 15.1400],
        [19.5800, 10.4700],
        [16.9200,  9.9640],
        [13.7840,  6.6900],
        [ 9.8350,  5.9500],
        [ 6.8800,  3.6800],
        [ 4.1560,  0.8320],
        [ 2.8750,  1.2400]], dtype=torch.float64)


In [4]:
#weights matrix
w = torch.randn(2, 2, requires_grad=True)
b = torch.randn(2, requires_grad=True)

print(w, "\n", b)

tensor([[0.4842, 0.0427],
        [0.6786, 1.5920]], requires_grad=True) 
 tensor([-0.7363, -0.6456], requires_grad=True)


In [5]:
def model(x):
    return x @ w.t() + b

In [6]:
predictions = model(inputs)

print(predictions)  

tensor([[3.7183, 6.1079],
        [3.6744, 5.6889],
        [3.1348, 4.8560],
        [3.5113, 5.3419],
        [3.5350, 5.3570],
        [3.2588, 4.9628],
        [3.4281, 5.1948],
        [3.0553, 4.6708]], grad_fn=<AddBackward0>)


In [7]:
#mean squared error
def mse(t1, t2):
    diff = t1 - t2
    #error is squared and added and divided by total number of elements
    return torch.sum(diff*diff)/diff.numel()

In [8]:
loss = mse(predictions, targets)
print(loss)

tensor(75.9565, dtype=torch.float64, grad_fn=<DivBackward0>)


In [9]:
loss.backward()

In [10]:
print(w)
print(w.grad)

print(b)
print(b.grad)


tensor([[0.4842, 0.0427],
        [0.6786, 1.5920]], requires_grad=True)
tensor([[-78.6762,  -1.2079],
        [-13.6540,  -0.4694]])
tensor([-0.7363, -0.6456], requires_grad=True)
tensor([-8.9505, -1.4732])


In [11]:
for i in range(600):
    preds = model(inputs)
    loss = mse(preds, targets)

    if(i%10==0):
        print(loss)

    loss.backward()
    
    with torch.no_grad():
        w -= w.grad * 1e-4
        b -= b.grad * 1e-4
        w.grad.zero_()
        b.grad.zero_()

tensor(75.9565, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(69.3758, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(64.2686, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(59.8716, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(56.0861, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(52.8271, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(50.0212, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(47.6055, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(45.5258, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(43.7352, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(42.1936, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(40.8663, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(39.7235, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(38.7397, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(37.8925, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(37.1632, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(36.5352, dtype=to

In [12]:
print(w)
print(preds)

tensor([[1.5281, 0.0855],
        [0.8601, 1.6151]], requires_grad=True)
tensor([[13.4128,  7.7938],
        [13.2859,  7.3568],
        [11.5856,  6.3213],
        [12.7751,  6.9481],
        [12.8505,  6.9720],
        [11.9791,  6.4742],
        [12.5136,  6.7697],
        [11.3370,  6.1059]], grad_fn=<AddBackward0>)


In [13]:
predictions = preds*100000
print(predictions)

print(w)
print(b)

tensor([[1341282.1250,  779381.9375],
        [1328592.2500,  735677.1250],
        [1158558.5000,  632133.0625],
        [1277508.3750,  694814.6875],
        [1285046.7500,  697199.9375],
        [1197911.8750,  647423.0625],
        [1251362.1250,  676971.3750],
        [1133698.8750,  610589.1875]], grad_fn=<MulBackward0>)
tensor([[1.5281, 0.0855],
        [0.8601, 1.6151]], requires_grad=True)
tensor([-0.6273, -0.6315], requires_grad=True)


In [17]:
members = (8.92 *  1.2807 + 9 *0.0855) * 100000
users = (8.92*0.8601 +9*1.6151)*100000
print(members)
print(users)

1219334.4
2220799.2
