In [145]:
import torch
import pandas as pd

import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

In [146]:
inputs, targets = load_breast_cancer(return_X_y=True)

print(load_breast_cancer())

inputs[:100]

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
 

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [9.787e+00, 1.994e+01, 6.211e+01, ..., 2.381e-02, 1.934e-01,
        8.988e-02],
       [1.160e+01, 1.284e+01, 7.434e+01, ..., 8.449e-02, 2.772e-01,
        8.756e-02],
       [1.442e+01, 1.977e+01, 9.448e+01, ..., 1.565e-01, 2.718e-01,
        9.353e-02]])

In [147]:
print(inputs.shape, targets.shape)

(569, 30) (569,)


In [148]:
inputs_train, inputs_test, targets_train, targets_test = train_test_split(inputs, targets, test_size=0.2)

inputs_train

array([[2.059e+01, 2.124e+01, 1.378e+02, ..., 2.113e-01, 2.480e-01,
        8.999e-02],
       [1.757e+01, 1.505e+01, 1.150e+02, ..., 1.456e-01, 2.756e-01,
        7.919e-02],
       [1.126e+01, 1.983e+01, 7.130e+01, ..., 2.832e-02, 2.557e-01,
        7.613e-02],
       ...,
       [1.396e+01, 1.705e+01, 9.143e+01, ..., 1.374e-01, 3.068e-01,
        7.957e-02],
       [1.171e+01, 1.545e+01, 7.503e+01, ..., 7.864e-02, 2.765e-01,
        7.806e-02],
       [1.104e+01, 1.683e+01, 7.092e+01, ..., 7.431e-02, 2.998e-01,
        7.881e-02]])

In [149]:
inputs_train = StandardScaler().fit_transform(inputs_train)
inputs_test = StandardScaler().fit_transform(inputs_test)
inputs_train

array([[ 1.82010409,  0.45904778,  1.87682063, ...,  1.4470346 ,
        -0.67694633,  0.34212544],
       [ 0.96226557, -0.99035874,  0.93604341, ...,  0.45509361,
        -0.23495461, -0.24657485],
       [-0.83010563,  0.12889217, -0.86711293, ..., -1.3156041 ,
        -0.55363704, -0.41337327],
       ...,
       [-0.06316391, -0.52205292, -0.03650567, ...,  0.33128971,
         0.26468821, -0.22586132],
       [-0.70228201, -0.89669758, -0.71320508, ..., -0.55587091,
        -0.22054183, -0.30817034],
       [-0.89259718, -0.57356656, -0.88279255, ..., -0.62124541,
         0.15258886, -0.26728838]])

In [150]:
inputs_train = torch.from_numpy(inputs_train.astype(np.float32))
inputs_test = torch.from_numpy(inputs_test.astype(np.float32))
targets_train = torch.from_numpy(targets_train.astype(np.float32))
targets_test = torch.from_numpy(targets_test.astype(np.float32))
print(targets_test)
print(targets_test.shape)

tensor([1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1.,
        0., 1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1.,
        1., 1., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0., 0., 0., 1., 0.,
        1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1.,
        1., 1., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 0., 0., 1., 1.,
        1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 0.,
        1., 0., 1., 1., 0., 0.])
torch.Size([114])


In [151]:
targets_train = targets_train.reshape(-1,1)
targets_test = targets_test.reshape(-1,1)

print(targets_test)
print(targets_test.shape)

tensor([[1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
      

In [152]:
class LogisticRegression(torch.nn.Module):
    def __init__(self, n_input_features):
        super().__init__()
        self.linear = torch.nn.Linear(n_input_features, 1)
    
    def forward(self, x):
        target_predicted = torch.sigmoid(self.linear(x))
        return target_predicted

In [153]:
model = LogisticRegression(30)

In [154]:
#binary cross entropy loss
cross_entropy = torch.nn.BCELoss()
opt = torch.optim.SGD(model.parameters(), lr = 3e-3)

In [155]:
def fit(num_epoch,loss_function, optimizer,X_train,X_test,y_train,y_test):
    for epoch in range(num_epoch):
        y_pred = model(X_train)
        loss = loss_function(y_pred, y_train)
        
        loss.backward()
        
        optimizer.step()
        
        optimizer.zero_grad()
        
        if (epoch+1)%10 == 0:
            print("Epoch: ",epoch+1," Loss :",loss.item())
            
    with torch.no_grad():
        y_pred = model(X_test)
        y_pred_cls = y_pred.round()
        accuracy = y_pred_cls.eq(y_test).sum()/len(targets_test)
        print("Accuracy: ",accuracy.item())
        
    

In [156]:
fit(200, cross_entropy, opt, inputs_train, inputs_test,targets_train,targets_test)

Epoch:  10  Loss : 0.8474180102348328
Epoch:  20  Loss : 0.7717950940132141
Epoch:  30  Loss : 0.7082819938659668
Epoch:  40  Loss : 0.6550229787826538
Epoch:  50  Loss : 0.6102249026298523
Epoch:  60  Loss : 0.5723077058792114
Epoch:  70  Loss : 0.5399537086486816
Epoch:  80  Loss : 0.5120977163314819
Epoch:  90  Loss : 0.4878930449485779
Epoch:  100  Loss : 0.4666721224784851
Epoch:  110  Loss : 0.44790971279144287
Epoch:  120  Loss : 0.4311915934085846
Epoch:  130  Loss : 0.4161891043186188
Epoch:  140  Loss : 0.40263962745666504
Epoch:  150  Loss : 0.39033153653144836
Epoch:  160  Loss : 0.37909236550331116
Epoch:  170  Loss : 0.3687809109687805
Epoch:  180  Loss : 0.35927993059158325
Epoch:  190  Loss : 0.35049164295196533
Epoch:  200  Loss : 0.34233370423316956
Accuracy:  tensor(0.8860)
